### Feature Engineering 2

In [3]:
from util.data_aquisition import generate

In [4]:
data = generate(seasons=[2015, 2016, 2017, 2018], play_offs=[False])

Data is available on your system. Will be loaded from: C:\Users\GM\Desktop\IFT-6758\data\regular_season\2015-2016
Data is available on your system. Will be loaded from: C:\Users\GM\Desktop\IFT-6758\data\regular_season\2016-2017
Data is available on your system. Will be loaded from: C:\Users\GM\Desktop\IFT-6758\data\regular_season\2017-2018
Data is available on your system. Will be loaded from: C:\Users\GM\Desktop\IFT-6758\data\regular_season\2018-2019

#### Create new data frame (question 1 and 2)

In [5]:
import pandas as pd
import numpy as np
import math

In [6]:
#Old code; should be adjusted according to new task
Empty_Net = []
Game_ID = []
Game_Type = []
Event_ID = []
Event_Type = []
Power_Game = []
Team_Attack = []
Coordinate_X = []
Coordinate_Y = []
Period = []
Period_Time = []
Time = []
Shooters = []
Scorers = []
Goalies = []
Shoot_type = []
Home = []
Away = []
Home_Rink = []
#Last Event Features
Last_Event_ID = []
Last_Event_Type = []
Last_Coordinate_X = []
Last_Coordinate_Y = []
Last_Period = []
Last_Period_Time = []
Last_Time = []

for a in range(len(data.data)):
    for b in range(len(data.data[a]['data'])):
        for i in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'])):
            if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Shot' or data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Goal':
                #Ici ajouter les données relatives au last event (type_last, x_last etc..) en se référant
                #À i-1 au lieu de i.
                Last_Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['eventIdx'])
                Last_Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['result']['event'])
                Last_Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('x', np.nan))
                Last_Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('y', np.nan))
                Last_Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['period'])
                Last_Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['periodTime'])
                Last_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['dateTime'])
                #
                Game_ID.append(data.data[a]['data'][b]['gamePk'])
                Game_Type.append(data.data[a]['data'][b]['gameData']['game']['type'])
                Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['eventIdx'])
                Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'])
                Home.append(data.data[a]['data'][b]['gameData']['teams']['home']['name'])
                Away.append(data.data[a]['data'][b]['gameData']['teams']['away']['name'])
                if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodType'] =='SHOOTOUT':
                    Home_Rink.append(np.nan)
                else:
                    Home_Rink.append(data.data[a]['data'][b]['liveData']['linescore']['periods'][data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period']-1]['home'].get('rinkSide', np.nan))

                if 'strength' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Power_Game.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['strength']['name'])
                else:
                    Power_Game.append(np.nan)

                if 'emptyNet' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Empty_Net.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['emptyNet'])
                else:
                    Empty_Net.append(np.nan)
                Team_Attack.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['team']['name'])
                Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('x', np.nan))
                Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('y', np.nan))
                Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period'])
                Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodTime'])
                Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['dateTime'])
                Shoot_type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].get('secondaryType', np.nan))

                for j in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'])):
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Shooter':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Scorer':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Goalie':
                            Goalies.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])

            if len(Goalies) < len(Game_ID):
                Goalies.append(np.nan)


data_game = {'Game_ID': Game_ID, 'Game_Type': Game_Type, 'Event_ID': Event_ID, 'Last_Event_ID': Last_Event_ID, 'Home_Team': Home, 'Home_Rink': Home_Rink, 'Away_Team': Away, 'Event_Type': Event_Type, 'Last_Event_Type': Last_Event_Type, 'Shoot_Type': Shoot_type, 'Time': Time, 'Period': Period, 'Last_Period': Last_Period, 'Period_Time': Period_Time, 'Last_Period_Time': Last_Period_Time, 'Team_Attack': Team_Attack, 'Power_Game': Power_Game, 'Empty_Net': Empty_Net, 'Shooters_scorer': Shooters, 'Goalies': Goalies, 'X_Coordinate': Coordinate_X, 'Last_Coordinate_X': Last_Coordinate_X, 'Y_Coordinate': Coordinate_Y, 'Last_Coordinate_Y': Last_Coordinate_Y}
df = pd.DataFrame(data_game)
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Last_Period_Time,Team_Attack,Power_Game,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,00:40,Toronto Maple Leafs,NaN,NaN,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,00:58,Toronto Maple Leafs,NaN,NaN,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,01:05,Toronto Maple Leafs,NaN,NaN,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,01:35,Toronto Maple Leafs,NaN,NaN,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,02:32,Toronto Maple Leafs,NaN,NaN,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,15:04,San Jose Sharks,NaN,NaN,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,16:04,Colorado Avalanche,NaN,NaN,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,18:20,Colorado Avalanche,NaN,NaN,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,18:39,Colorado Avalanche,NaN,NaN,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,19:12,San Jose Sharks,Even,True,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0

#### Adding other features (question 3)

In [7]:
# Convert Period times to datetime
df['Period_Time'] = pd.to_datetime(df['Period_Time'])
df['Last_Period_Time'] = pd.to_datetime(df['Last_Period_Time'])
# Broadcasting: subtract last period time to period time
df['Time_Between_Events']= df['Period_Time']-df['Last_Period_Time']

In [8]:
#Only display in seconds, wierd cause here seconds where treated as minutes so divided by 60
df['Time_Between_Events'] = (df['Time_Between_Events'].astype('timedelta64[s]')/60).astype(str)

In [9]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Team_Attack,Power_Game,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Toronto Maple Leafs,NaN,NaN,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0,11.0
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,Toronto Maple Leafs,NaN,NaN,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0,7.0
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,Toronto Maple Leafs,NaN,NaN,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0,1.0
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Toronto Maple Leafs,NaN,NaN,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0,18.0
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,Toronto Maple Leafs,NaN,NaN,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,San Jose Sharks,NaN,NaN,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,Colorado Avalanche,NaN,NaN,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,Colorado Avalanche,NaN,NaN,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0,19.0
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,Colorado Avalanche,NaN,NaN,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0,1.0
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,San Jose Sharks,Even,True,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0,3.0

In [10]:
def transform_X(row):
    '''
    Given a row of the original data frame, this function transforms the coordinate X depending on the position of
    the teams in the rink. Since at the end the data is presented in a half-rink (we arbitrarily choose that
    this is the right half of the rink), when the attacking team plays on the right side of the rink , i.e
    the opponent's goal is on the left side, we need to flip the x coordinate.
    '''
    if str(row['Home_Rink']) == 'nan': #In case the rinkside information is not available, we assume the shot
        #is taken from the side that is the closest to the opponent's goal.
        return np.absolute(row['X_Coordinate'])

    else: #Otherwise we use rinkside information to determine whether to flip X coordinate as described above.
        if row['Home_Team'] == row['Team_Attack']:
            if row['Home_Rink'] == 'right':
                return -(row['X_Coordinate'])
            else:
                return row['X_Coordinate']
        else:
            if row['Home_Rink'] == 'left':
                return -(row['X_Coordinate'])
            else:
                return row['X_Coordinate']

In [11]:
# Transform X coordinates to one side of the rink
df['X_Transformed'] = df.apply(transform_X, axis=1)

In [12]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Power_Game,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,NaN,NaN,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0,11.0,55.0
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,NaN,NaN,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0,7.0,79.0
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,NaN,NaN,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0,1.0,75.0
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,NaN,NaN,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0,18.0,55.0
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,NaN,NaN,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,NaN,NaN,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0,67.0
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,NaN,NaN,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0,78.0
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,NaN,NaN,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0,19.0,82.0
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,NaN,NaN,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0,1.0,81.0
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,Even,True,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0,3.0,74.0

In [13]:
def transform_last_X(row):
    '''
    Given a row of the original data frame, this function transforms the Last coordinate X depending on the position of
    the teams in the rink. Since at the end the data is presented in a half-rink (we arbitrarily choose that
    this is the right half of the rink), when the attacking team plays on the right side of the rink , i.e
    the opponent's goal is on the left side, we need to flip the x coordinate.
    '''
    if str(row['Home_Rink']) == 'nan': #In case the rinkside information is not available, we assume the shot
        #is taken from the side that is the closest to the opponent's goal.
        return np.absolute(row['Last_Coordinate_X'])

    else: #Otherwise we use rinkside information to determine whether to flip X coordinate as described above.
        if row['Home_Team'] == row['Team_Attack']:
            if row['Home_Rink'] == 'right':
                return -(row['Last_Coordinate_X'])
            else:
                return row['Last_Coordinate_X']
        else:
            if row['Home_Rink'] == 'left':
                return -(row['Last_Coordinate_X'])
            else:
                return row['Last_Coordinate_X']

In [14]:
# Transform Last Coordinates X to one side of the rink
df['Last_X_Transformed'] = df.apply(transform_last_X, axis=1)

In [15]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,NaN,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0,11.0,55.0,-94.0
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,NaN,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0,7.0,79.0,37.0
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,NaN,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0,1.0,75.0,79.0
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,NaN,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0,18.0,55.0,91.0
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,NaN,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0,61.0,69.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,NaN,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0,67.0,29.0
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,NaN,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0,78.0,69.0
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,NaN,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0,19.0,82.0,71.0
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,NaN,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0,1.0,81.0,82.0
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,True,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0,3.0,74.0,-65.0

In [16]:
def get_distance(row):
    ''' Given a row of the original dataframe, this function computes the distance between one event and its preceding event'''
    return ((row['X_Coordinate']-row['Last_Coordinate_X'])**2+(row['Y_Coordinate']-row['Last_Coordinate_Y'])**2)**(1/2)

In [17]:
# Get the distance between all pairs of events and preceding events
df['Distance']= df.apply(get_distance, axis=1)

In [18]:
# Alternative: more efficient, but less flexible
# ((df['X_Coordinate']-df['Last_Coordinate_X'])**2+(df['Y_Coordinate']-df['Last_Coordinate_Y'])**2)**(1/2)

In [19]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0,11.0,55.0,-94.0,154.275727
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0,7.0,79.0,37.0,50.477718
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0,1.0,75.0,79.0,4.123106
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0,18.0,55.0,91.0,79.605276
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0,61.0,69.0,22.472205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0,67.0,29.0,66.030296
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0,78.0,69.0,24.698178
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0,19.0,82.0,71.0,12.529964
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0,1.0,81.0,82.0,9.055385
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0,3.0,74.0,-65.0,144.100659

In [20]:
# Creat a boolean column testing whether the last event type was a shot
df['Rebond'] = df['Last_Event_Type'] == 'Shot'

In [21]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance,Rebond
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Carey Price,-55.0,94.0,6.0,-34.0,11.0,55.0,-94.0,154.275727,False
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,Carey Price,-79.0,-37.0,0.0,-28.0,7.0,79.0,37.0,50.477718,False
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,Carey Price,-75.0,-79.0,-1.0,0.0,1.0,75.0,79.0,4.123106,True
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Carey Price,-55.0,-91.0,-36.0,35.0,18.0,55.0,91.0,79.605276,False
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0,61.0,69.0,22.472205,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0,67.0,29.0,66.030296,False
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0,78.0,69.0,24.698178,False
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,Martin Jones,-82.0,-71.0,10.0,4.0,19.0,82.0,71.0,12.529964,False
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,Martin Jones,-81.0,-82.0,1.0,10.0,1.0,81.0,82.0,9.055385,True
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,NaN,74.0,-65.0,4.0,-34.0,3.0,74.0,-65.0,144.100659,False

In [22]:
def get_angle(row):
    '''
    Given a row on the original dataframe, this function computes the angle of the shot. It first tests whether the last event was a Rebond. If false, it returns NAN. If true, it then tests whether the X_Transformed coordinate of the event is 89 (the x coordinate of the net). If also true, it returns an angle of either -90 or 90 degrees depending on its y coordinate. If false, it computes the angle according to the right triangle properties.
    '''
    # if row['Rebond']:
    if row['X_Transformed'] ==89:
        return 90*row['Y_Coordinate']/(np.abs(row['Y_Coordinate']))
    else :
        return np.arctan((row['Y_Coordinate']/(89-row['X_Transformed'])))*180/math.pi
    # else:
    #     return np.nan

In [23]:
#Set the angles of the events (Wierd message appears...)
df['Angle'] = df.apply(get_angle, axis = 1)

C:\Users\GM\AppData\Local\Temp\ipykernel_27588\4159003376.py:7: RuntimeWarning: invalid value encountered in double_scalars
  return 90*row['Y_Coordinate']/(np.abs(row['Y_Coordinate']))

In [24]:
# df[df['Angle'].isnull()]

In [25]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance,Rebond,Angle
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,-55.0,94.0,6.0,-34.0,11.0,55.0,-94.0,154.275727,False,NaN
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,-79.0,-37.0,0.0,-28.0,7.0,79.0,37.0,50.477718,False,NaN
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,-75.0,-79.0,-1.0,0.0,1.0,75.0,79.0,4.123106,True,-4.085617
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,-55.0,-91.0,-36.0,35.0,18.0,55.0,91.0,79.605276,False,NaN
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,-61.0,-69.0,-1.0,-22.0,5.0,61.0,69.0,22.472205,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,67.0,29.0,-19.0,35.0,33.0,67.0,29.0,66.030296,False,NaN
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,-78.0,-69.0,1.0,-22.0,29.0,78.0,69.0,24.698178,False,NaN
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,-82.0,-71.0,10.0,4.0,19.0,82.0,71.0,12.529964,False,NaN
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,-81.0,-82.0,1.0,10.0,1.0,81.0,82.0,9.055385,True,7.125016
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,74.0,-65.0,4.0,-34.0,3.0,74.0,-65.0,144.100659,False,NaN

In [26]:
def get_last_angle(row):
    '''
    Given a row on the original dataframe, this function computes the angle of the last shot. It first tests whether the last event was a Rebond. If false, it returns NAN. If true, it then tests whether the Last_X_Transformed coordinate of the event is 89 (the x coordinate of the net). If also true, it returns an angle of either -90 or 90 degrees depending on the last event's y coordinate. If false, it computes the angle of the last shot according to the right triangle properties.
    '''
    if row['Rebond']:
        if row['Last_X_Transformed'] ==89:
            return 90*row['Last_Coordinate_Y']/(np.abs(row['Last_Coordinate_Y']))
        else :
            return np.arctan((row['Last_Coordinate_Y']/(89-row['Last_X_Transformed'])))*180/math.pi
    else:
        return np.nan

In [27]:
# Set a column for the angles of the last events that were shots
df['Last_Angle'] = df.apply(get_last_angle, axis = 1)

In [28]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance,Rebond,Angle,Last_Angle
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,94.0,6.0,-34.0,11.0,55.0,-94.0,154.275727,False,NaN,NaN
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,-37.0,0.0,-28.0,7.0,79.0,37.0,50.477718,False,NaN,NaN
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,-79.0,-1.0,0.0,1.0,75.0,79.0,4.123106,True,-4.085617,0.00000
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,-91.0,-36.0,35.0,18.0,55.0,91.0,79.605276,False,NaN,NaN
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,-69.0,-1.0,-22.0,5.0,61.0,69.0,22.472205,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,29.0,-19.0,35.0,33.0,67.0,29.0,66.030296,False,NaN,NaN
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,-69.0,1.0,-22.0,29.0,78.0,69.0,24.698178,False,NaN,NaN
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,-71.0,10.0,4.0,19.0,82.0,71.0,12.529964,False,NaN,NaN
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,-82.0,1.0,10.0,1.0,81.0,82.0,9.055385,True,7.125016,55.00798
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,-65.0,4.0,-34.0,3.0,74.0,-65.0,144.100659,False,NaN,NaN

In [29]:
# Compute the angular difference between the angle of the present event and the angle of the last events (both shots).
df['Delta_Angle'] = df['Angle']-df['Last_Angle']

In [30]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance,Rebond,Angle,Last_Angle,Delta_Angle
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,6.0,-34.0,11.0,55.0,-94.0,154.275727,False,NaN,NaN,NaN
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,0.0,-28.0,7.0,79.0,37.0,50.477718,False,NaN,NaN,NaN
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,-1.0,0.0,1.0,75.0,79.0,4.123106,True,-4.085617,0.00000,-4.085617
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,-36.0,35.0,18.0,55.0,91.0,79.605276,False,NaN,NaN,NaN
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,-1.0,-22.0,5.0,61.0,69.0,22.472205,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,-19.0,35.0,33.0,67.0,29.0,66.030296,False,NaN,NaN,NaN
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,1.0,-22.0,29.0,78.0,69.0,24.698178,False,NaN,NaN,NaN
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,10.0,4.0,19.0,82.0,71.0,12.529964,False,NaN,NaN,NaN
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,1.0,10.0,1.0,81.0,82.0,9.055385,True,7.125016,55.00798,-47.882963
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,4.0,-34.0,3.0,74.0,-65.0,144.100659,False,NaN,NaN,NaN

In [31]:
# Compute the speed between an event and a last event
df['Speed'] = df['Distance']/pd.to_numeric(df['Time_Between_Events'])

In [32]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance,Rebond,Angle,Last_Angle,Delta_Angle,Speed
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,-34.0,11.0,55.0,-94.0,154.275727,False,NaN,NaN,NaN,14.025066
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,-28.0,7.0,79.0,37.0,50.477718,False,NaN,NaN,NaN,7.211103
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,0.0,1.0,75.0,79.0,4.123106,True,-4.085617,0.00000,-4.085617,4.123106
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,35.0,18.0,55.0,91.0,79.605276,False,NaN,NaN,NaN,4.422515
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,-22.0,5.0,61.0,69.0,22.472205,False,NaN,NaN,NaN,4.494441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,35.0,33.0,67.0,29.0,66.030296,False,NaN,NaN,NaN,2.000918
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,-22.0,29.0,78.0,69.0,24.698178,False,NaN,NaN,NaN,0.851661
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,4.0,19.0,82.0,71.0,12.529964,False,NaN,NaN,NaN,0.659472
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,10.0,1.0,81.0,82.0,9.055385,True,7.125016,55.00798,-47.882963,9.055385
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,-34.0,3.0,74.0,-65.0,144.100659,False,NaN,NaN,NaN,48.033553

#### Bonus part: Powerplay information

#### Data submission to comet.ml (question 4)