### Feature Engineering 2

In [1]:
from util.data_aquisition import generate

In [2]:
data = generate(seasons=[2015, 2016, 2017, 2018], play_offs=[False])

Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2015-2016
Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2016-2017
Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2017-2018
Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2018-2019

#### Create new data frame (question 1 and 2)

In [3]:
import pandas as pd
import numpy as np
import math

In [6]:
#Old code; should be adjusted according to new task
Empty_Net = []
Game_ID = []
Game_Type = []
Event_ID = []
Event_Type = []
Power_Game = []
Team_Attack = []
Coordinate_X = []
Coordinate_Y = []
Period = []
Period_Time = []
Time = []
Shooters = []
Scorers = []
Goalies = []
Shoot_type = []
Home = []
Away = []
Home_Rink = []
#Last Event Features
Last_Event_ID = []
Last_Event_Type = []
Last_Coordinate_X = []
Last_Coordinate_Y = []
Last_Period = []
Last_Period_Time = []
Last_Time = []

for a in range(len(data.data)):
    for b in range(len(data.data[a]['data'])):
        for i in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'])):
            if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Shot' or data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Goal':
                #Ici ajouter les données relatives au last event (type_last, x_last etc..) en se référant
                #À i-1 au lieu de i.
                Last_Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['eventIdx'])
                Last_Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['result']['event'])
                Last_Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('x', np.nan))
                Last_Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('y', np.nan))
                Last_Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['period'])
                Last_Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['periodTime'])
                Last_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['dateTime'])
                #
                Game_ID.append(data.data[a]['data'][b]['gamePk'])
                Game_Type.append(data.data[a]['data'][b]['gameData']['game']['type'])
                Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['eventIdx'])
                Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'])
                Home.append(data.data[a]['data'][b]['gameData']['teams']['home']['name'])
                Away.append(data.data[a]['data'][b]['gameData']['teams']['away']['name'])
                if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodType'] =='SHOOTOUT':
                    Home_Rink.append(np.nan)
                else:
                    Home_Rink.append(data.data[a]['data'][b]['liveData']['linescore']['periods'][data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period']-1]['home'].get('rinkSide', np.nan))

                if 'strength' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Power_Game.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['strength']['name'])
                else:
                    Power_Game.append(np.nan)

                if 'emptyNet' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Empty_Net.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['emptyNet'])
                else:
                    Empty_Net.append(np.nan)
                Team_Attack.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['team']['name'])
                Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('x', np.nan))
                Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('y', np.nan))
                Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period'])
                Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodTime'])
                Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['dateTime'])
                Shoot_type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].get('secondaryType', np.nan))

                for j in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'])):
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Shooter':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Scorer':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Goalie':
                            Goalies.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])

            if len(Goalies) < len(Game_ID):
                Goalies.append(np.nan)


data_game = {'Game_ID': Game_ID, 'Game_Type': Game_Type, 'Event_ID': Event_ID, 'Last_Event_ID': Last_Event_ID, 'Home_Team': Home, 'Home_Rink': Home_Rink, 'Away_Team': Away, 'Event_Type': Event_Type, 'Last_Event_Type': Last_Event_Type, 'Shoot_Type': Shoot_type, 'Time': Time, 'Period': Period, 'Last_Period': Last_Period, 'Period_Time': Period_Time, 'Last_Period_Time': Last_Period_Time, 'Team_Attack': Team_Attack, 'Power_Game': Power_Game, 'Empty_Net': Empty_Net, 'Shooters_scorer': Shooters, 'Goalies': Goalies, 'X_Coordinate': Coordinate_X, 'Last_Coordinate_X': Last_Coordinate_X, 'Y_Coordinate': Coordinate_Y, 'Last_Coordinate_Y': Last_Coordinate_Y}
df = pd.DataFrame(data_game)
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Last_Period_Time,Team_Attack,Power_Game,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,00:40,Toronto Maple Leafs,NaN,NaN,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,00:58,Toronto Maple Leafs,NaN,NaN,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,01:05,Toronto Maple Leafs,NaN,NaN,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,01:35,Toronto Maple Leafs,NaN,NaN,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,02:32,Toronto Maple Leafs,NaN,NaN,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,15:04,San Jose Sharks,NaN,NaN,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,16:04,Colorado Avalanche,NaN,NaN,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,18:20,Colorado Avalanche,NaN,NaN,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,18:39,Colorado Avalanche,NaN,NaN,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,19:12,San Jose Sharks,Even,True,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0

#### Adding other features (question 3)

In [7]:
# Convert Period times to datetime
df['Period_Time'] = pd.to_datetime(df['Period_Time'])
df['Last_Period_Time'] = pd.to_datetime(df['Last_Period_Time'])
# Broadcasting: subtract last period time to period time
df['Time_Between_Events']= df['Period_Time']-df['Last_Period_Time']

In [8]:
#Only display in seconds, wierd cause here seconds where treated as minutes so divided by 60
df['Time_Between_Events'] = (df['Time_Between_Events'].astype('timedelta64[s]')/60).astype(str)

In [9]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Team_Attack,Power_Game,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Toronto Maple Leafs,NaN,NaN,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0,11.0
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,Toronto Maple Leafs,NaN,NaN,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0,7.0
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,Toronto Maple Leafs,NaN,NaN,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0,1.0
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Toronto Maple Leafs,NaN,NaN,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0,18.0
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,Toronto Maple Leafs,NaN,NaN,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,San Jose Sharks,NaN,NaN,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,Colorado Avalanche,NaN,NaN,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,Colorado Avalanche,NaN,NaN,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0,19.0
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,Colorado Avalanche,NaN,NaN,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0,1.0
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,San Jose Sharks,Even,True,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0,3.0

In [10]:
def transform_X(row):
    '''
    Given a row of the original data frame, this function transforms the coordinate X depending on the position of
    the teams in the rink. Since at the end the data is presented in a half-rink (we arbitrarily choose that
    this is the right half of the rink), when the attacking team plays on the right side of the rink , i.e
    the opponent's goal is on the left side, we need to flip the x coordinate.
    '''
    if str(row['Home_Rink']) == 'nan': #In case the rinkside information is not available, we assume the shot
        #is taken from the side that is the closest to the opponent's goal.
        return np.absolute(row['X_Coordinate'])

    else: #Otherwise we use rinkside information to determine whether to flip X coordinate as described above.
        if row['Home_Team'] == row['Team_Attack']:
            if row['Home_Rink'] == 'right':
                return -(row['X_Coordinate'])
            else:
                return row['X_Coordinate']
        else:
            if row['Home_Rink'] == 'left':
                return -(row['X_Coordinate'])
            else:
                return row['X_Coordinate']

In [11]:
# Transform X coordinates to one side of the rink
df['X_Transformed'] = df.apply(transform_X, axis=1)

In [12]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Power_Game,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,NaN,NaN,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0,11.0,55.0
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,NaN,NaN,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0,7.0,79.0
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,NaN,NaN,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0,1.0,75.0
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,NaN,NaN,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0,18.0,55.0
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,NaN,NaN,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,NaN,NaN,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0,67.0
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,NaN,NaN,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0,78.0
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,NaN,NaN,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0,19.0,82.0
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,NaN,NaN,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0,1.0,81.0
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,Even,True,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0,3.0,74.0

In [13]:
def transform_last_X(row):
    '''
    Given a row of the original data frame, this function transforms the Last coordinate X depending on the position of
    the teams in the rink. Since at the end the data is presented in a half-rink (we arbitrarily choose that
    this is the right half of the rink), when the attacking team plays on the right side of the rink , i.e
    the opponent's goal is on the left side, we need to flip the x coordinate.
    '''
    if str(row['Home_Rink']) == 'nan': #In case the rinkside information is not available, we assume the shot
        #is taken from the side that is the closest to the opponent's goal.
        return np.absolute(row['Last_Coordinate_X'])

    else: #Otherwise we use rinkside information to determine whether to flip X coordinate as described above.
        if row['Home_Team'] == row['Team_Attack']:
            if row['Home_Rink'] == 'right':
                return -(row['Last_Coordinate_X'])
            else:
                return row['Last_Coordinate_X']
        else:
            if row['Home_Rink'] == 'left':
                return -(row['Last_Coordinate_X'])
            else:
                return row['Last_Coordinate_X']

In [14]:
# Transform Last Coordinates X to one side of the rink
df['Last_X_Transformed'] = df.apply(transform_last_X, axis=1)

In [15]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,NaN,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0,11.0,55.0,-94.0
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,NaN,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0,7.0,79.0,37.0
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,NaN,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0,1.0,75.0,79.0
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,NaN,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0,18.0,55.0,91.0
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,NaN,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0,61.0,69.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,NaN,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0,67.0,29.0
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,NaN,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0,78.0,69.0
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,NaN,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0,19.0,82.0,71.0
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,NaN,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0,1.0,81.0,82.0
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,True,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0,3.0,74.0,-65.0

In [16]:
def get_distance(row):
    ''' Given a row of the original dataframe, this function computes the distance between one event and its preceding event'''
    return ((row['X_Coordinate']-row['Last_Coordinate_X'])**2+(row['Y_Coordinate']-row['Last_Coordinate_Y'])**2)**(1/2)

In [17]:
# Get the distance between all pairs of events and preceding events
df['Distance']= df.apply(get_distance, axis=1)

In [18]:
# Alternative: more efficient, but less flexible
# ((df['X_Coordinate']-df['Last_Coordinate_X'])**2+(df['Y_Coordinate']-df['Last_Coordinate_Y'])**2)**(1/2)

In [19]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Brad Boyes,Carey Price,-55.0,94.0,6.0,-34.0,11.0,55.0,-94.0,154.275727
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,Nazem Kadri,Carey Price,-79.0,-37.0,0.0,-28.0,7.0,79.0,37.0,50.477718
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,Nazem Kadri,Carey Price,-75.0,-79.0,-1.0,0.0,1.0,75.0,79.0,4.123106
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Daniel Winnik,Carey Price,-55.0,-91.0,-36.0,35.0,18.0,55.0,91.0,79.605276
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,Joffrey Lupul,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0,61.0,69.0,22.472205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,Joe Pavelski,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0,67.0,29.0,66.030296
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,Gabriel Landeskog,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0,78.0,69.0,24.698178
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,Gabriel Landeskog,Martin Jones,-82.0,-71.0,10.0,4.0,19.0,82.0,71.0,12.529964
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,Carl Soderberg,Martin Jones,-81.0,-82.0,1.0,10.0,1.0,81.0,82.0,9.055385
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,Micheal Haley,NaN,74.0,-65.0,4.0,-34.0,3.0,74.0,-65.0,144.100659

In [20]:
# Creat a boolean column testing whether the last event type was a shot
df['Rebond'] = df['Last_Event_Type'] == 'Shot'

In [21]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance,Rebond
0,2015020001,R,7,6,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Carey Price,-55.0,94.0,6.0,-34.0,11.0,55.0,-94.0,154.275727,False
1,2015020001,R,9,8,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Giveaway,Snap Shot,...,Carey Price,-79.0,-37.0,0.0,-28.0,7.0,79.0,37.0,50.477718,False
2,2015020001,R,10,9,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Shot,Snap Shot,...,Carey Price,-75.0,-79.0,-1.0,0.0,1.0,75.0,79.0,4.123106,True
3,2015020001,R,13,12,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Hit,Wrist Shot,...,Carey Price,-55.0,-91.0,-36.0,35.0,18.0,55.0,91.0,79.605276,False
4,2015020001,R,21,20,Toronto Maple Leafs,right,Montréal Canadiens,Shot,Faceoff,Tip-In,...,Carey Price,-61.0,-69.0,-1.0,-22.0,5.0,61.0,69.0,22.472205,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021271,R,276,275,San Jose Sharks,left,Colorado Avalanche,Shot,Giveaway,Slap Shot,...,Semyon Varlamov,67.0,29.0,-19.0,35.0,33.0,67.0,29.0,66.030296,False
311102,2018021271,R,281,280,San Jose Sharks,left,Colorado Avalanche,Shot,Faceoff,Wrist Shot,...,Martin Jones,-78.0,-69.0,1.0,-22.0,29.0,78.0,69.0,24.698178,False
311103,2018021271,R,291,290,San Jose Sharks,left,Colorado Avalanche,Shot,Missed Shot,Wrist Shot,...,Martin Jones,-82.0,-71.0,10.0,4.0,19.0,82.0,71.0,12.529964,False
311104,2018021271,R,292,291,San Jose Sharks,left,Colorado Avalanche,Shot,Shot,Wrist Shot,...,Martin Jones,-81.0,-82.0,1.0,10.0,1.0,81.0,82.0,9.055385,True
311105,2018021271,R,298,297,San Jose Sharks,left,Colorado Avalanche,Goal,Takeaway,Wrist Shot,...,NaN,74.0,-65.0,4.0,-34.0,3.0,74.0,-65.0,144.100659,False

In [ ]:
def get_angle(row):
    '''
    Given a row on the original dataframe, this function computes the angle of the shot. It first tests whether the last event was a Rebond. If false, it returns NAN. If true, it then tests whether the X_Transformed coordinate of the event is 89 (the x coordinate of the net). If also true, it returns an angle of either -90 or 90 degrees depending on its y coordinate. If false, it computes the angle according to the right triangle properties.
    '''
    # if row['Rebond']:
    if row['X_Transformed'] ==89:
        return 90*row['Y_Coordinate']/(np.abs(row['Y_Coordinate']))
    else :
        return np.arctan((row['Y_Coordinate']/(89-row['X_Transformed'])))*180/math.pi
    # else:
    #     return np.nan

In [ ]:
#Set the angles of the events (Wierd message appears...)
df['Angle'] = df.apply(get_angle, axis = 1)

In [ ]:
# df[df['Angle'].isnull()]

In [ ]:
df

In [ ]:
def get_last_angle(row):
    '''
    Given a row on the original dataframe, this function computes the angle of the last shot. It first tests whether the last event was a Rebond. If false, it returns NAN. If true, it then tests whether the Last_X_Transformed coordinate of the event is 89 (the x coordinate of the net). If also true, it returns an angle of either -90 or 90 degrees depending on the last event's y coordinate. If false, it computes the angle of the last shot according to the right triangle properties.
    '''
    if row['Rebond']:
        if row['Last_X_Transformed'] ==89:
            return 90*row['Last_Coordinate_Y']/(np.abs(row['Last_Coordinate_Y']))
        else :
            return np.arctan((row['Last_Coordinate_Y']/(89-row['Last_X_Transformed'])))*180/math.pi
    else:
        return np.nan

In [ ]:
# Set a column for the angles of the last events that were shots
df['Last_Angle'] = df.apply(get_last_angle, axis = 1)

In [ ]:
df

In [ ]:
# Compute the angular difference between the angle of the present event and the angle of the last events (both shots).
df['Delta_Angle'] = df['Angle']-df['Last_Angle']

In [ ]:
df

In [ ]:
# Compute the speed between an event and a last event
df['Speed'] = df['Distance']/pd.to_numeric(df['Time_Between_Events'])

In [ ]:
df

#### Bonus part: Powerplay information

In [13]:
import datetime

In [14]:
def reset_penalty_stack():
    """
    Will be called on each period start to reset the penalty_stack to empty state.
    """
    penalty_stack = { #Dictionary contaning current penalty information. Will be updated in each event.
        "home": [], #List of current active penalites for the home team
        "away": [], #Same for away team. Format of penalty tuple: (playerID, penaltyMinutes, penaltySeverity, periodTime)
        "team_on_power_play": "none", #Current team that is on power play, can be "home", "away" or "none"
        "power_play_since": datetime.timedelta(minutes =0, seconds = 0), #Period time of the start of the current powerplay
    }
    return penalty_stack
#Penalty types compared from least severe to most severe
RANKED_PENALTIES = ["Minor", "Double Minor", "Major", "Misconduct", "Game Misconduct", "Match"]

In [15]:
def penalty_stack_update_on_any_event(penalty_stack,period_time):
    """
    Update function, will be the first one to be called on any event.
    Updates penalty_stack by deleting penalties which time is over.
    A penalty is represented as a tuple (player_id, penalty_minutes, penalty_severity, period_time).
    """
    #Preprocessing
    separated_time = period_time.split(":")
    period_time = datetime.timedelta(minutes=int(separated_time[0]), seconds=int(separated_time[1]))

    #Delete outdated penalties
    for team in ["home", "away"]:
        penalties_to_delete = []
        for i,penalty  in enumerate(penalty_stack[team]):
            penalty_duration = datetime.timedelta(minutes=penalty[1])
            penalty_start = penalty[3]
            penalty_severity = penalty[2]
            if penalty_start+penalty_duration <= period_time:
                penalties_to_delete.append(penalty)
            elif penalty_severity == "Double Minor":
                #Double minors which have less than 2 mins left on the clock become minor penalties
                if period_time-penalty_start> datetime.timedelta(minutes=2):
                    new_minor_penalty = (penalty[0],2,"Minor", penalty_start+datetime.timedelta(minutes=2))
                    penalty_stack[team][i]=new_minor_penalty
        for penalty in penalties_to_delete: #actually removing the penalties
            penalty_stack[team].remove(penalty)


    old_team_on_power_play = penalty_stack["team_on_power_play"]
    #Determining who's in powerplay now
    if len(penalty_stack["home"]) > len(penalty_stack["away"]): #In this case away is on powerplay
        penalty_stack["team_on_power_play"] = "away"
    elif len(penalty_stack["home"]) < len(penalty_stack["away"]):
        penalty_stack["team_on_power_play"] = "home"
    else:
        penalty_stack["team_on_power_play"] = "none"

    #Now if the team on power play changed, we set "power_play_since" to be perod_time, else we do nothing,
    #Thus preserving the start time of the already existing power_play
    if old_team_on_power_play != penalty_stack["team_on_power_play"]:
        if penalty_stack["team_on_power_play"] == "none":
            #Makes more sense to reset "power_play_since" to zero here, although can be set
            #to anything we want.
            penalty_stack["power_play_since"] = datetime.timedelta(minutes =0, seconds = 0)
        else :
            penalty_stack["power_play_since"] =  period_time

    return penalty_stack

In [16]:
def penalty_stack_update_on_penalty_event(penalty_stack, penalty_severity, penalty_minutes, period_time, player_id, team, home):
    """
    Update function to be called on each penalty event. Updates the penalty_stack.
    """
    #Pre-processing
    concerned_team = "home" if team==home else "away"

    if penalty_severity in ["Minor", "Bench Minor"]:
        if penalty_minutes==4:
            penalty_severity="Double Minor" #Creating Double Minor Severity for convenience.
        else:
            penalty_severity="Minor" #Bench Minor Penalties have same effect on the team as minor.
    if penalty_severity=="Match":
        penalty_minutes=5 #Match penalties are registered for 10 mins for statistical
        #Purposes but the team stays shorthanded for 5 minutes only. (Piazza question @95)

    separated_time = period_time.split(":")
    period_time = datetime.timedelta(minutes=int(separated_time[0]), seconds=int(separated_time[1]))

    if player_id in [penalty[0] for penalty in penalty_stack[concerned_team]] and penalty_severity!="Penalty Shot":
        #If player already has a penalty
        #Apply the most severe one (Piazza question @96)
        index_of_players_penalty = [penalty[0] for penalty in penalty_stack[concerned_team]].index(player_id)
        if RANKED_PENALTIES.index(penalty_severity) > RANKED_PENALTIES.index(penalty_stack[concerned_team][index_of_players_penalty][2]):
            if penalty_severity in ["Misconduct", "Game Misconduct"]:
                #Those penalties are more severe but the team doesn't stay shorthanded with them.
                #Since those penalties override the already announced one, we could simply delete the latter
                penalty_stack[concerned_team].pop(index_of_players_penalty)
            else:
                penalty_stack[concerned_team].pop(index_of_players_penalty)
                penalty_stack[concerned_team].append((player_id, penalty_minutes, penalty_severity, period_time))


    else: #Treat this as a penalty for a new player
        if penalty_severity in ["Misconduct", "Game Misconduct", "Penalty Shot"]:
            return penalty_stack #Only penalties of type "Minor", "Bench Minor", "Major", and "Match" can make a team
        #Short-handed. Other types of penalties exclude a particular player but allows the team to replace him
        #With someone else. Penalty shots constitute no exclusions.

        #Adding penalty to the concerned team.
        #If already 2 penalties exist, ignore the new penalty
        if len(penalty_stack[concerned_team])<2:
            penalty_stack[concerned_team].append((player_id, penalty_minutes, penalty_severity, period_time))

    old_team_on_power_play = penalty_stack["team_on_power_play"]
    #Determining who's in powerplay now
    if len(penalty_stack["home"]) > len(penalty_stack["away"]): #In this case away is on powerplay
        penalty_stack["team_on_power_play"] = "away"
    elif len(penalty_stack["home"]) < len(penalty_stack["away"]):
        penalty_stack["team_on_power_play"] = "home"
    else:
        penalty_stack["team_on_power_play"] = "none"

    #Now if the team on power play changed, we set "power_play_since" to be perod_time, else we do nothing,
    #Thus preserving the start time of the already existing power_play
    if old_team_on_power_play != penalty_stack["team_on_power_play"]:
        if penalty_stack["team_on_power_play"] == "none":
            #Makes more sense to reset "power_play_since" to zero here, although can be set
            #to anything we want.
            penalty_stack["power_play_since"] = datetime.timedelta(minutes =0, seconds = 0)
        else :
            penalty_stack["power_play_since"] =  period_time

    return penalty_stack

In [17]:
def penalty_stack_update_on_goal_event(penalty_stack, period_time, scoring_team, home):
    """
    Update function to be called each goal event.
    """
    conceding_team = "away" if scoring_team==home else "home"
    scoring_team = "away" if conceding_team=="home" else "away"
    separated_time = period_time.split(":")
    period_time = datetime.timedelta(minutes=int(separated_time[0]), seconds=int(separated_time[1]))
    #If the conceding_team is short-handed, delete the minor penalty corresponding
    #to the least amout of time on the clock (Double minors with t>2 mins become minors)
    #List of minor penalties or double minors with time >2 mins
    #Here double minors with time <=2 mins have been automatically transformed to minors in previous
    #update calls.
    if len(penalty_stack[conceding_team]) > len(penalty_stack[scoring_team]):
        candidate_penalties_idxs = [i for i in range(len(penalty_stack[conceding_team])) if
                                    penalty_stack[conceding_team][i][2] in ["Minor", "Double Minor"]]
        if len(candidate_penalties_idxs) == 0:
            return penalty_stack #No Minor or Double Minor penalties to be stopped
        else:
            #Look for the penalty with the shortest time on clock (for double minor consider
            #duration = 2)
            shortest_penalty_index = candidate_penalties_idxs[0]
            shortest_penalty_time_on_clock = datetime.timedelta(minutes=2)-\
                                             (period_time-penalty_stack[conceding_team][shortest_penalty_index][3])
            for idx in candidate_penalties_idxs:
                time_on_clock = datetime.timedelta(minutes=2)-\
                                             (period_time-penalty_stack[conceding_team][idx][3])
                if time_on_clock<shortest_penalty_time_on_clock:
                    time_on_clock = shortest_penalty_time_on_clock
                    shortest_penalty_index = idx

            if penalty_stack[conceding_team][shortest_penalty_index][2]=="Double Minor":
                #Double Minor is replaced by a minor
                double_minor_penalty = penalty_stack[conceding_team].pop(shortest_penalty_index)
                new_minor_penalty = (double_minor_penalty[0],2,"Minor", period_time)
                penalty_stack[conceding_team].append(new_minor_penalty)
            else:
                #Just delete the minor penalty
                penalty_stack[conceding_team].pop(shortest_penalty_index)

        old_team_on_power_play = penalty_stack["team_on_power_play"]
        #Determining who's in powerplay now
        if len(penalty_stack["home"]) > len(penalty_stack["away"]): #In this case away is on powerplay
            penalty_stack["team_on_power_play"] = "away"
        elif len(penalty_stack["home"]) < len(penalty_stack["away"]):
            penalty_stack["team_on_power_play"] = "home"
        else:
            penalty_stack["team_on_power_play"] = "none"

        #Now if the team on power play changed, we set "power_play_since" to be perod_time, else we do nothing,
        #Thus preserving the start time of the already existing power_play
        if old_team_on_power_play != penalty_stack["team_on_power_play"]:
            if penalty_stack["team_on_power_play"] == "none":
                #Makes more sense to reset "power_play_since" to zero here, although can be set
                #to anything we want.
                penalty_stack["power_play_since"] = datetime.timedelta(minutes =0, seconds = 0)
            else :
                penalty_stack["power_play_since"] =  period_time




    return penalty_stack

In [26]:
#Old code; should be adjusted according to new task
Empty_Net = []
Game_ID = []
Game_Type = []
Event_ID = []
Event_Type = []
Power_Game = []
Team_Attack = []
Coordinate_X = []
Coordinate_Y = []
Period = []
Period_Time = []
Time = []
Shooters = []
Scorers = []
Goalies = []
Shoot_type = []
Home = []
Away = []
Home_Rink = []
#Last Event Features
Last_Event_ID = []
Last_Event_Type = []
Last_Coordinate_X = []
Last_Coordinate_Y = []
Last_Period = []
Last_Period_Time = []
Last_Time = []
Powerplay_Since = []
Friendly_Non_Goalies = []
Opponent_Non_Goalies = []

penalty_stack = reset_penalty_stack()
for a in range(len(data.data)):
    for b in range(len(data.data[a]['data'])):
        for i in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'])):
            if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Period Start':
                penalty_stack = reset_penalty_stack()
            #Make the on any event update to delete outdated penalties
            penalty_stack = penalty_stack_update_on_any_event(
                penalty_stack,
                data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodTime']
            )
            if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Shot' or data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Goal':
                #Features corresponding to last event
                Last_Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['eventIdx'])
                Last_Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['result']['event'])
                Last_Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('x', np.nan))
                Last_Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('y', np.nan))
                Last_Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['period'])
                Last_Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['periodTime'])
                Last_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['dateTime'])
                #Features corresponding to current event
                Game_ID.append(data.data[a]['data'][b]['gamePk'])
                Game_Type.append(data.data[a]['data'][b]['gameData']['game']['type'])
                Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['eventIdx'])
                Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'])
                Home.append(data.data[a]['data'][b]['gameData']['teams']['home']['name'])
                Away.append(data.data[a]['data'][b]['gameData']['teams']['away']['name'])
                if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodType'] =='SHOOTOUT':
                    Home_Rink.append(np.nan)
                else:
                    Home_Rink.append(data.data[a]['data'][b]['liveData']['linescore']['periods'][data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period']-1]['home'].get('rinkSide', np.nan))

                if 'strength' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Power_Game.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['strength']['name'])
                else:
                    Power_Game.append(np.nan)

                if 'emptyNet' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Empty_Net.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['emptyNet'])
                else:
                    Empty_Net.append(np.nan)
                Team_Attack.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['team']['name'])
                Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('x', np.nan))
                Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('y', np.nan))
                Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period'])
                Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodTime'])
                Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['dateTime'])
                Shoot_type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].get('secondaryType', np.nan))

                for j in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'])):
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Shooter':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Scorer':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Goalie':
                            Goalies.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])

                #Add data related to penalties
                period_time = Period_Time[-1]
                separated_time = period_time.split(":")
                period_time = datetime.timedelta(minutes=int(separated_time[0]), seconds=int(separated_time[1]))
                if penalty_stack["power_play_since"]== datetime.timedelta(minutes =0, seconds = 0):
                    Powerplay_Since.append(datetime.timedelta(minutes =0, seconds = 0))
                else:
                    Powerplay_Since.append(period_time-penalty_stack["power_play_since"])
                team_attack_is = "home" if Team_Attack[-1]==Home[-1] else "away"
                team_opponent_is = "home" if team_attack_is=="away" else "away"
                Friendly_Non_Goalies.append(5-len(penalty_stack[team_attack_is]))
                Opponent_Non_Goalies.append(5-len(penalty_stack[team_opponent_is]))
                #Now, if the shot was actually a goal, update the penalt_stack according
                #To the rule of deleting a minor penalty when opponent scores
                if Event_Type[-1]=='Goal':
                    penalty_stack = penalty_stack_update_on_goal_event(
                        penalty_stack,
                        Period_Time[-1],
                        Team_Attack[-1],
                        Home[-1]
                    )
            elif data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Penalty':
                penalty_stack = penalty_stack_update_on_penalty_event(
                    penalty_stack,
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['penaltySeverity'],
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['penaltyMinutes'],
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodTime'],
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][0]['player']['id'],
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['team']['name'],
                    data.data[a]['data'][b]['gameData']['teams']['home']['name'])

            if len(Goalies) < len(Game_ID):
                Goalies.append(np.nan)


data_game = {'Game_ID': Game_ID, 'Game_Type': Game_Type, 'Event_ID': Event_ID, 'Last_Event_ID': Last_Event_ID, 'Home_Team': Home, 'Home_Rink': Home_Rink, 'Away_Team': Away, 'Event_Type': Event_Type, 'Last_Event_Type': Last_Event_Type, 'Shoot_Type': Shoot_type, 'Time': Time, 'Period': Period, 'Last_Period': Last_Period, 'Period_Time': Period_Time, 'Last_Period_Time': Last_Period_Time, 'Team_Attack': Team_Attack, 'Power_Game': Power_Game, 'Empty_Net': Empty_Net, 'Shooters_scorer': Shooters, 'Goalies': Goalies, 'X_Coordinate': Coordinate_X, 'Last_Coordinate_X': Last_Coordinate_X, 'Y_Coordinate': Coordinate_Y, 'Last_Coordinate_Y': Last_Coordinate_Y, 'Powerplay_Since': Powerplay_Since, 'Friendly_Non_Goalies': Friendly_Non_Goalies, 'Opponent_Non_Goalies': Opponent_Non_Goalies}
df = pd.DataFrame(data_game)
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Powerplay_Since,Friendly_Non_Goalies,Opponent_Non_Goalies
0,2015020364,R,5,4,Nashville Predators,left,Arizona Coyotes,Shot,Hit,Wrist Shot,...,NaN,Filip Forsberg,Mike Smith,50.0,-78.0,20.0,-38.0,0 days,5,5
1,2015020364,R,12,10,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Wrist Shot,...,NaN,Cody Hodgson,Mike Smith,77.0,69.0,6.0,-22.0,0 days,5,5
2,2015020364,R,13,11,Nashville Predators,left,Arizona Coyotes,Shot,Takeaway,Wrist Shot,...,NaN,Craig Smith,Mike Smith,86.0,35.0,-12.0,-2.0,0 days,5,5
3,2015020364,R,18,17,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Backhand,...,NaN,Viktor Arvidsson,Mike Smith,82.0,69.0,7.0,22.0,0 days,5,5
4,2015020364,R,32,31,Nashville Predators,left,Arizona Coyotes,Shot,Blocked Shot,Wrist Shot,...,NaN,Seth Jones,Mike Smith,48.0,85.0,-10.0,-11.0,0 days,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021002,R,285,284,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,NaN,Zach Hyman,Linus Ullmark,-47.0,75.0,13.0,0.0,0 days,5,5
311102,2018021002,R,286,285,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Backhand,...,NaN,Jeff Skinner,Frederik Andersen,74.0,-47.0,-2.0,13.0,0 days,5,5
311103,2018021002,R,287,286,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,NaN,Jeff Skinner,Frederik Andersen,78.0,74.0,5.0,-2.0,0 days,5,5
311104,2018021002,R,292,291,Toronto Maple Leafs,right,Buffalo Sabres,Goal,Takeaway,Backhand,...,True,Mitchell Marner,NaN,-68.0,96.0,35.0,32.0,0 days,5,5
311105,2018021002,R,296,295,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Blocked Shot,Wrist Shot,...,NaN,Frederik Gauthier,Linus Ullmark,-43.0,-64.0,-12.0,14.0,0 days,5,5

In [27]:
df.Opponent_Non_Goalies.value_counts()

5    260187
4     48123
3      2796
Name: Opponent_Non_Goalies, dtype: int64

In [28]:
df.Friendly_Non_Goalies.value_counts()

5    293175
4     17237
3       694
Name: Friendly_Non_Goalies, dtype: int64

In [32]:
df.Powerplay_Since.value_counts()

0 days 00:00:00    260107
0 days 00:00:08       661
0 days 00:00:07       579
0 days 00:00:10       568
0 days 00:00:06       559
                    ...
0 days 00:04:21         1
0 days 00:04:07         1
0 days 00:04:00         1
0 days 00:07:06         1
0 days 00:04:17         1
Name: Powerplay_Since, Length: 304, dtype: int64

#### Data submission to comet.ml (question 4)

In [34]:
df[df.Powerplay_Since<datetime.timedelta(seconds = 1)].Power_Game.value_counts()

Even            22301
Power Play        430
Short Handed       65
Name: Power_Game, dtype: int64

In [37]:
df.Powerplay_Since.info()

<class 'pandas.core.series.Series'>
RangeIndex: 311106 entries, 0 to 311105
Series name: Powerplay_Since
Non-Null Count   Dtype
--------------   -----
311106 non-null  timedelta64[ns]
dtypes: timedelta64[ns](1)
memory usage: 2.4 MB

In [38]:
pd.to_datetime(df.Powerplay_Since).dt.time

TypeError: dtype timedelta64[ns] cannot be converted to datetime64[ns]